#! /bin/sh

sxhkd &

bspc monitor -d web term edit music chat other1 other2 other3 other4 other5

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Start programs
compton& 
wal -c -i ~/.bg&
conky -c ~/.config/conky.conf&
polybar thebar& 
dunst& 
nm-applet&

rofi -show run -dpi 192 -font "Ubuntu 18"
